[package]
name = "web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo = "0.7"
wasm-bindgen = "0.2"
yew = "0.19"

[dependencies.web-sys]
version = "0.3"
features = [
    "Element",
    "HtmlCollection",
]
